# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_msgs/control_msgs/control_cmd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bridge_msgs.basic_msgs import header_pb2 as bridge__msgs_dot_basic__msgs_dot_header__pb2
from bridge_msgs.chassis_msgs import chassis_pb2 as bridge__msgs_dot_chassis__msgs_dot_chassis__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*bridge_msgs/control_msgs/control_cmd.proto\x12\x0fprescan.control\x1a#bridge_msgs/basic_msgs/header.proto\x1a&bridge_msgs/chassis_msgs/chassis.proto\"\xd6\x01\n\x0e\x43ontrolCommand\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x16.prescan.common.Header\x12\x10\n\x08throttle\x18\x03 \x01(\x01\x12\r\n\x05\x62rake\x18\x04 \x01(\x01\x12\x10\n\x08steering\x18\x07 \x01(\x01\x12\x11\n\ttar_speed\x18\t \x01(\x01\x12\x18\n\x10tar_acceleration\x18\n \x01(\x01\x12<\n\rgear_location\x18\x14 \x01(\x0e\x32%.prescan.chassis.Chassis.GearPosition')



_CONTROLCOMMAND = DESCRIPTOR.message_types_by_name['ControlCommand']
ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLCOMMAND,
  '__module__' : 'bridge_msgs.control_msgs.control_cmd_pb2'
  # @@protoc_insertion_point(class_scope:prescan.control.ControlCommand)
  })
_sym_db.RegisterMessage(ControlCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLCOMMAND._serialized_start=141
  _CONTROLCOMMAND._serialized_end=355
# @@protoc_insertion_point(module_scope)
