# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge_msgs/basic_msgs/geometry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%bridge_msgs/basic_msgs/geometry.proto\x12\x0eprescan.common\")\n\x07Point2D\x12\x0e\n\x01x\x18\x01 \x01(\x01:\x03nan\x12\x0e\n\x01y\x18\x02 \x01(\x01:\x03nan\"9\n\x07Point3D\x12\x0e\n\x01x\x18\x01 \x01(\x01:\x03nan\x12\x0e\n\x01y\x18\x02 \x01(\x01:\x03nan\x12\x0e\n\x01z\x18\x03 \x01(\x01:\x03nan\"@\n\x08PointLLH\x12\x10\n\x03lat\x18\x01 \x01(\x01:\x03nan\x12\x10\n\x03lon\x18\x02 \x01(\x01:\x03nan\x12\x10\n\x03\x61lt\x18\x03 \x01(\x01:\x03nan\"F\n\x0bOrientation\x12\x11\n\x04roll\x18\x01 \x01(\x01:\x03nan\x12\x12\n\x05pitch\x18\x02 \x01(\x01:\x03nan\x12\x10\n\x03yaw\x18\x03 \x01(\x01:\x03nan\"@\n\x06\x42\x42ox2D\x12\x0c\n\x04xmin\x18\x01 \x01(\x01\x12\x0c\n\x04ymin\x18\x02 \x01(\x01\x12\x0c\n\x04xmax\x18\x03 \x01(\x01\x12\x0c\n\x04ymax\x18\x04 \x01(\x01\"N\n\rBoundingBox3D\x12\x13\n\x06size_x\x18\x01 \x01(\x01:\x03nan\x12\x13\n\x06size_y\x18\x02 \x01(\x01:\x03nan\x12\x13\n\x06size_z\x18\x03 \x01(\x01:\x03nan\"P\n\nQuaternion\x12\x0f\n\x02qx\x18\x01 \x01(\x01:\x03nan\x12\x0f\n\x02qy\x18\x02 \x01(\x01:\x03nan\x12\x0f\n\x02qz\x18\x03 \x01(\x01:\x03nan\x12\x0f\n\x02qw\x18\x04 \x01(\x01:\x03nan\"1\n\x07Polygon\x12&\n\x05point\x18\x01 \x03(\x0b\x32\x17.prescan.common.Point3D')



_POINT2D = DESCRIPTOR.message_types_by_name['Point2D']
_POINT3D = DESCRIPTOR.message_types_by_name['Point3D']
_POINTLLH = DESCRIPTOR.message_types_by_name['PointLLH']
_ORIENTATION = DESCRIPTOR.message_types_by_name['Orientation']
_BBOX2D = DESCRIPTOR.message_types_by_name['BBox2D']
_BOUNDINGBOX3D = DESCRIPTOR.message_types_by_name['BoundingBox3D']
_QUATERNION = DESCRIPTOR.message_types_by_name['Quaternion']
_POLYGON = DESCRIPTOR.message_types_by_name['Polygon']
Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), {
  'DESCRIPTOR' : _POINT2D,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.Point2D)
  })
_sym_db.RegisterMessage(Point2D)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), {
  'DESCRIPTOR' : _POINT3D,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.Point3D)
  })
_sym_db.RegisterMessage(Point3D)

PointLLH = _reflection.GeneratedProtocolMessageType('PointLLH', (_message.Message,), {
  'DESCRIPTOR' : _POINTLLH,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.PointLLH)
  })
_sym_db.RegisterMessage(PointLLH)

Orientation = _reflection.GeneratedProtocolMessageType('Orientation', (_message.Message,), {
  'DESCRIPTOR' : _ORIENTATION,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.Orientation)
  })
_sym_db.RegisterMessage(Orientation)

BBox2D = _reflection.GeneratedProtocolMessageType('BBox2D', (_message.Message,), {
  'DESCRIPTOR' : _BBOX2D,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.BBox2D)
  })
_sym_db.RegisterMessage(BBox2D)

BoundingBox3D = _reflection.GeneratedProtocolMessageType('BoundingBox3D', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOX3D,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.BoundingBox3D)
  })
_sym_db.RegisterMessage(BoundingBox3D)

Quaternion = _reflection.GeneratedProtocolMessageType('Quaternion', (_message.Message,), {
  'DESCRIPTOR' : _QUATERNION,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.Quaternion)
  })
_sym_db.RegisterMessage(Quaternion)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'bridge_msgs.basic_msgs.geometry_pb2'
  # @@protoc_insertion_point(class_scope:prescan.common.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINT2D._serialized_start=57
  _POINT2D._serialized_end=98
  _POINT3D._serialized_start=100
  _POINT3D._serialized_end=157
  _POINTLLH._serialized_start=159
  _POINTLLH._serialized_end=223
  _ORIENTATION._serialized_start=225
  _ORIENTATION._serialized_end=295
  _BBOX2D._serialized_start=297
  _BBOX2D._serialized_end=361
  _BOUNDINGBOX3D._serialized_start=363
  _BOUNDINGBOX3D._serialized_end=441
  _QUATERNION._serialized_start=443
  _QUATERNION._serialized_end=523
  _POLYGON._serialized_start=525
  _POLYGON._serialized_end=574
# @@protoc_insertion_point(module_scope)
